// frontend/src/components/AnimatedMoney.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { formatCOP } from '../utils/format'

const props = defineProps<{ value: number; duration?: number; prefix?: string }>()

const display = ref(0)
let raf = 0

function animate(to: number) {
  cancelAnimationFrame(raf)
  const from = display.value
  const start = performance.now()
  const dur = props.duration ?? 850
  const ease = (t: number) => 1 - Math.pow(1 - t, 3)

  const step = (now: number) => {
    const p = Math.min((now - start) / dur, 1)
    display.value = from + (to - from) * ease(p)
    if (p < 1) raf = requestAnimationFrame(step)
  }
  raf = requestAnimationFrame(step)
}

onMounted(() => animate(props.value))
watch(() => props.value, (v) => animate(v))
onBeforeUnmount(() => cancelAnimationFrame(raf))
</script>

<template>
  <span>{{ (prefix ?? '') + formatCOP(Math.round(display)) }}</span>
</template>

// frontend/src/app/components/animated-money.component.ts
import { Component, Input, OnChanges, OnDestroy, SimpleChanges, signal } from '@angular/core';

import { formatCOP } from '../core/format';

/** Anima el conteo de un valor numerico y lo formatea como COP. */
@Component({
  selector: 'app-animated-money',
  standalone: true,
  template: `<span>{{ display() }}</span>`,
})
export class AnimatedMoneyComponent implements OnChanges, OnDestroy {
  @Input({ required: true }) value = 0;
  @Input() duration = 850;
  @Input() prefix = '';

  private raf = 0;
  private current = 0;
  readonly display = signal('$0');

  ngOnChanges(changes: SimpleChanges): void {
    if ('value' in changes) this.animate(this.value);
  }

  ngOnDestroy(): void {
    cancelAnimationFrame(this.raf);
  }

  private animate(to: number): void {
    cancelAnimationFrame(this.raf);
    const from = this.current;
    const start = performance.now();
    const dur = this.duration;
    const ease = (t: number) => 1 - Math.pow(1 - t, 3);

    const step = (now: number) => {
      const p = Math.min((now - start) / dur, 1);
      this.current = from + (to - from) * ease(p);
      this.display.set(this.prefix + formatCOP(Math.round(this.current)));
      if (p < 1) this.raf = requestAnimationFrame(step);
    };
    this.raf = requestAnimationFrame(step);
  }
}
